### ISSUE TITLE
[QUESTION] sklearn vs numpy SVD

### ISSUE THREAD

**Issue by cakiki** [TutteInstitute/topicnaming#8]
Hello,

I was wondering whether there was a reason why [this line](https://github.com/TutteInstitute/topicnaming/blob/main/topicnaming/topic_naming.py#L184) uses scikit-learn's randomised SVD whereas [this line](https://github.com/TutteInstitute/topicnaming/blob/main/topicnaming/topic_naming.py#L292) uses numpy's.

**Comment by lmcinnes** [comment]
Mostly this is pretty young code that hasn't been properly refactored yet. In this case I think the best explanation is that there was some expectation that the matrices for the first case could get quite large (but we only need the first several components from the SVD, while in the seocn the matrices should be small so the numpy algorithm that returns the full (rather than top k) SVD should be fine.

**Comment by cakiki** [comment]
Thank you Leland, I really appreciate you always taking the time to explain things!
